### ISSUE TITLE
Lack of information for disabled applicants

### ISSUE THREAD

**Issue by mintkrab** [madetech/handbook#541]
This is my first time using GitHub (I signed up to file this issue) so apologies if I’m doing it wrong. 

I’m potentially interested in applying to MadeTech. I’m also disabled, and surprised by some things in your job adverts and handbook - things that made me feel I shouldn’t apply. I’ve started telling employers when their recruitment processes or information discourages or prevents me from applying in the hope that this feedback is useful and improves things for others in future.

Here are the things I noticed. I would also like to recommend you map out the user journey for disabled applicants, as you might spot further issues as well. 

1. No contact details for if you need to request an alternative format. The only contact email I can find anywhere on your site is a general one (contact@). I don’t feel comfortable emailing a general inbox about my disability - I’d prefer to disclose that to the right contact first time, and to know it will be picked up in time. I don’t need an alternative format but, if someone does, they are likely to feel the same. I’m sure you would too! This is also why I’ve filed a GitHub issue - I would have preferred to email a relevant contact but there wasn’t one.

2. A way to request reasonable adjustments when you apply. Lots of employers have found ways to ask about this and keep the information separate so it’s only shared if you get shortlisted. You don’t have a space for this. This makes things uncertain for me. If you invite me to interview, will you ask if I need adjustments or is the onus on me to ask? Will it be possible to ask, or will you send me an email that blocks this in some way (for example it’s just an automated link to book an interview slot) so I can only ask via that general email I mentioned in point 1? And if you invite me to interview without having a space to request reasonable adjustments, will you at least offer me a choice of dates and times rather than assuming I can accept any one? So for me that’s a lot of emotional labour for me while you retain all the power. Which makes it harder for me to apply and also raises questions for me about how well you’ll support me if I work for you.

3. I can’t find information in your handbook about supporting disabled employees and providing reasonable adjustments. There’s some very official legal stuff in your diversity policy but that doesn’t tell me what, if anything, you have in place to actively support disabled employees in terms of systems and processes. It would be great if you had that and linked it from your job ads. From what I can see you have info about all kinds of things but not that. It’s great that the intention is there to support people - but is the system set up for this kind of support? How much emotional labour will I have to do? It feels worrying that I can’t find this. Why would you not want that process to be clear and visible? After all most adjustments are either free or very cheap!

4. Your sickness policy is very strange. You say you require a doctor’s note after four days, but this isn’t something GPs do - you can only get a free fit note after seven days normally (or 28 right now due to covid). You would need to pay after four days and I don’t think my surgery would do this at all. Obviously I don’t plan to be ill, but policies on sickness can convey fundamental things about an employer’s attitude to health and disability. I’m left wondering how this policy was decided as I’ve never seen anything like it in my life. Do you realise that it’s very hard to get a sick note after four days? Why do you want one? Will you pay for it? 

I really hope this feedback is useful.

**Comment by lburnett88** [comment]
@mintkrab hello, I work at Made Tech as a Project Manager, so not in HR or recruitment. I just saw your pull request come through, and wanted to drop you a quick message to let you know our office is closed for Christmas until 4th January, so somebody will respond to your feedback properly when the office reopens (I didn't want you to think it was being ignored). In the meantime, thank you for taking time to submit your feedback, it will definitely be taken seriously and we will learn from this and strive to do better. We are continuously working to promote diversity, inclusion and belonging, and are updating practices as we learn more.

**Comment by jameshollo** [comment]
@mintkrab Thanks very much for bearing with us! We have plans to address each of these points that we’d like to share here. If you don’t mind, we’ll also share this discussion on social media so others can contribute. 

If anyone would like to share more feedback, they’re very welcome to. They can do that here, or via [Twitter](https://twitter.com/madetech) or [LinkedIn](https://www.linkedin.com/company/madetech), or by emailing our Head of Talent, Kate Phillips, at <kate.phillips@madetech.com>.

**1. No contact details if you need to request an alternative format**

Great point! When someone applies for a role, they’re assigned a talent partner who can provide other formats. We’ll update all our job descriptions so it’s clear that these are available when needed.

**2. A way to request reasonable adjustments when you apply**

We’ll be clearer on all job descriptions that adjustments can be made. And that this is something a candidate’s talent partner can help with. We email this info to candidates, but totally agree it should appear on the job descriptions too. 

We’ll also make clear that we can increase the time allotted for interviews. And that alternative formats are available for any related docs. We’ll invite candidates to raise any other adjustments needed too.

**3. No information in handbook about supporting disabled employees and providing reasonable adjustments**

Sorry about this. We want to be clear that everyone is welcome to apply for roles at Made Tech. We’ll update our Equality, Diversity & Inclusion at Made Tech page so it’s clear that we understand people have varying needs. And we'll be clearer that we’ll do everything we can to support them. We’ll also highlight that candidates can talk to our people team about how we can meet their needs.

**4. Sickness policy**

This was incorrect, sorry. We shouldn’t (and hopefully don’t!) ask team members to provide fit notes after 4 days. We’ve made the pull request to adjust this to match current guidance. For now, we think it’s better to link to the guidance than state a number of days as the number is likely to change again soon.

**Next steps**

We’ve started work to address these points, and hope to complete them in days rather than weeks. But we welcome more feedback in the meantime!

Thanks so much for sharing your feedback with us. It will help us do better for candidates in the future, so we really appreciate it. Best of luck if you have or intend to apply for a role with us – we hope you do!

**Comment by cob16** [comment]
related to point 4 https://github.com/madetech/handbook/pull/554#pullrequestreview-854406199

**Comment by jameshollo** [comment]
Related to point 2 #555

**Comment by jameshollo** [comment]
This issue has been closed automatically as the linked pull requests have been merged. But please do add to the comments (feel free to tag me) or create a new issue if there's more feedback for us. We plan to have job descriptions updated in the next week. Thanks so much again.

**Comment by mintkrab** [comment]
@jameshollo thanks for your replies etc. The following confused me:

“ 1. No contact details if you need to request an alternative format

Great point! When someone applies for a role, they’re assigned a talent partner who can provide other formats. We’ll update all our job descriptions so it’s clear that these are available when needed.”

This doesn’t make sense or solve the problem. I asked how someone who needs an alternative format in order to apply can contact you to ask for this. You have answered with information about something that happens after you apply - but I am asking about people who need this to apply.

Please provide a mechanism for requesting alternative formats and reasonable adjustments before you apply.

**Comment by jameshollo** [comment]
@mintkrab Ah, sorry about that. Totally hear you. We'll take another look.

**Comment by mintkrab** [comment]
@jameshollo this is why I recommend you map out the steps involved. I really think it will help you understand some of what’s going wrong.

**Comment by jameshollo** [comment]
@mintkrab Thank you! We have a programme manager joining in March who can map out these hiring journeys and process to make sure gaps are identified and filled. But of course, we want to do better in the meantime, too. If we were to add a note like this to the top of every job description, would that address the main thrust of this particular point?

> If you need this job description in another format, or other support in applying, please email talent@madetech.com.”

**Comment by mintkrab** [comment]
@jameshollo yes! That looks great!

**Comment by jameshollo** [comment]
I've checked in and can see the job descriptions aren't yet updated. I'm really sorry about that. We're chasing this up today.
