### ISSUE TITLE
Size of handbook

### ISSUE THREAD

**Issue by lukemorton** [madetech/handbook#55]
Firstly, I'm very happy to see the handbook increasing in popularity, encouraging conversations about company culture and process, all out in the open. HELLS YEAH.

As the use of the handbook and therefore the content grows it'll become increasingly hard to consume and find things. I'd like to start a bit of a discussion around how we can keep this under control.

A few questions:

- How much detail should the handbook go into a subject? Should the default be just to create a single README per subject?
- Can we give a bit of an overview of every section in the main README? Is that helpful? Should we just keep it as a table of contents?
- Do we expect a new hires, whether potential or soon to be onboarded, to be able to read the handbook in a sitting to understand the company? I certainly was able to read the handbook of my first company in a sitting. It gave me a wide breadth of understanding whilst going into quite a bit of detail at points on particular subjects.

**Comment by davidwinter** [comment]
Do we need to review the current content and for the root README to have a decent/working contents page linking to the various content?

Then have a policy where new PR's must include an edit to the contents page too.

**Comment by chrisblackburn** [comment]
Another questions: how can we be better at culling less useful stuff? More content = more content going stale

**Comment by idabmat** [comment]
As someone who just went through it recently in order to figure out what the company was about, I think I should contribute here.

Personally the more content the better. I think it's more a matter of how to structure the content than a matter of how much information should go into it. What do you think about making the handbook into a [gitbook](https://www.gitbook.com) ?

The main advantage I see is to allow for easier navigation of the content, which in turn allows new/prospective members to prioritize what they should be reading up on, and helps existing members better spot content that may be going stale.

**Comment by zuren** [comment]
I think a gitbook is a great idea, it would probably make it easier to spot where we should be adding contents pages too.

**Comment by lukemorton** [comment]
@idabmat Hi and great idea! GitHub is okay for navigating, but not as easy as something like gitbook.

There are also alternatives we can consider like https://readthedocs.org/ or using a static site generator like Jekyll and GitHub to host a HTML version.

**Comment by RoryMacDonald** [comment]
I agree with Igor that the more content we have in here, the better. If things change, we should update, but I don't think we should remove stuff just because it's not the current flavour of the month. 

I would love to get the handbook to the point where it contains much more detail about how we do things. For example, our delivery approach is quite unique and I suspect it's quite difficult for new starters to get their heads around the fast paced delivery side of things. I think our handbook should be talking about this and bizops and all the other things we do. The support process is quite a good example of detailed approach / write up.

I'd love to get this published on our website one day, as is great for recruitment and people who are interested in more of the inner workings of Made Tech.
