### ISSUE TITLE
Escalation framework

### ISSUE THREAD

**Issue by lukemorton** [madetech/handbook#80]
I'd like to write a framework/document for the following:

- What to do when I need to escalate an issue? I.e. disagreement between staff, disagreement with leadership, when someone has been wronged, etc.
- Who can I talk to when I have a problem?
- Is there an external body I can receive help from?

**Comment by craigjbass** [comment]
How would we approach this from a Self-Management perspective:

* It’s impossible to change other people. We can only change ourselves.
* We take ownership for our thoughts, beliefs, words, and actions.
* We don’t spread rumors.
* We don’t talk behind someone’s back.
* We resolve disagreements one-on-one and don’t drag other people into the problem.
* We don’t blame problems on others. When we feel like blaming, we take it as an invitation to reflect on how we might be part of the problem (and the solution).
* We focus on strengths more than weaknesses, on opportunities more than problems.

# Steps

1. First, methods are developed to help people bring tensions to the surface.
2. Second, clearly defined conflict resolution processes are available to help people safely confront each other when needed.
3. Third, most self-managing organizations train every new recruit in conflict resolution and interpersonal skills.

# For example:
In the first phase, the two people sit together and try to sort it out privately.
If they can’t find a solution agreeable to both, they nominate a colleague they both trust to act as a mediator. The mediator doesn’t impose a decision. Rather he or she supports the participants in coming to their own solution.
If mediation fails, a panel of topic-relevant colleagues is convened. Again the panel does not impose a solution.
If resolution is not found, the founder or president might be called into the panel to add to the panel’s moral weight (but again, not to impose a solution).

# Training in Interpersonal skills
Because effective conflict resolution skills are so central in self-managing organizations, many organizations train all their colleagues in interpersonal skills to enable them to deal gracefully with conflict. Generally in their first weeks at work, new hires are given foundational training including: self-management, deep listening, dealing constructively with conflict and creating a safe environment. For instance, companies like ESBZ and Buurtzorg train colleagues in Nonviolent Communication developed by Marshal Rosenberg.

[source](http://www.reinventingorganizationswiki.com/Conflict_resolution)
